


// ✅ Page constants
const MARVEL = "1index.html";
const DC = "2index.html";
const ZOMBIE = "3index.html";
const TRANSFORMERS = "4index.html";
const ROMANTIC = "5index.html";

// ✅ Movies Data
const movies = [

    // 🔴 MARVEL
    { name: "Spider-Man", category: "Marvel", page: MARVEL },
    { name: "Spider-Man 2", category: "Marvel", page: MARVEL },
    { name: "Spider-Man 3", category: "Marvel", page: MARVEL },
    { name: "Spider-Man: Far From Home", category: "Marvel", page: MARVEL },
    { name: "Spider-Man: Homecoming", category: "Marvel", page: MARVEL },
    { name: "Spider-Man: No Way Home", category: "Marvel", page: MARVEL },
    { name: "Iron Man", category: "Marvel", page: MARVEL },
    { name: "Iron Man 2", category: "Marvel", page: MARVEL },
    { name: "Iron Man 3", category: "Marvel", page: MARVEL },
    { name: "Captain America: The First Avenger", category: "Marvel", page: MARVEL },
    { name: "Captain America: The Winter Soldier", category: "Marvel", page: MARVEL },
    { name: "Captain America: Civil War", category: "Marvel", page: MARVEL },
    { name: "Thor", category: "Marvel", page: MARVEL },
    { name: "Thor: The Dark World", category: "Marvel", page: MARVEL },
    { name: "Thor: Ragnarok", category: "Marvel", page: MARVEL },
    { name: "Thor: Love & Thunder", category: "Marvel", page: MARVEL },
    { name: "Venom", category: "Marvel", page: MARVEL },
    { name: "Venom: Let There Be Carnage", category: "Marvel", page: MARVEL },
    { name: "Venom: The Last Dance", category: "Marvel", page: MARVEL },
    { name: "Thunderbolts", category: "Marvel", page: MARVEL },
    { name: "The Avengers", category: "Marvel", page: MARVEL },
    { name: "Avengers: Age of Ultron", category: "Marvel", page: MARVEL },
    { name: "Avengers: Infinity War", category: "Marvel", page: MARVEL },
    { name: "Avengers: Endgame", category: "Marvel", page: MARVEL },
    { name: "Ant-Man", category: "Marvel", page: MARVEL },
    { name: "Ant-Man & The Wasp", category: "Marvel", page: MARVEL },
    { name: "Ant-Man & The Wasp: Quantumania", category: "Marvel", page: MARVEL },
    { name: "Ghost Rider", category: "Marvel", page: MARVEL },
    { name: "Ghost Rider: Spirit of Vengeance", category: "Marvel", page: MARVEL },
    { name: "Deadpool", category: "Marvel", page: MARVEL },
    { name: "Deadpool 2", category: "Marvel", page: MARVEL },
    { name: "Deadpool & Wolverine", category: "Marvel", page: MARVEL },
    { name: "Black Panther", category: "Marvel", page: MARVEL },
    { name: "Black Panther: Wakanda Forever", category: "Marvel", page: MARVEL },
    { name: "Black Widow", category: "Marvel", page: MARVEL },
    { name: "WandaVision", category: "Marvel", page: MARVEL },
    { name: "Daredevil", category: "Marvel", page: MARVEL },
    { name: "Eternals", category: "Marvel", page: MARVEL },
    { name: "Moon Knight", category: "Marvel", page: MARVEL },
    { name: "Hawkeye", category: "Marvel", page: MARVEL },

    // 🔵 DC
    { name: "Lucifer", category: "DC", page: DC },
    { name: "Batwoman", category: "DC", page: DC },
    { name: "Batman Begins", category: "DC", page: DC },
    { name: "The Batman", category: "DC", page: DC },
    { name: "The Flash", category: "DC", page: DC },
    { name: "DC League of Super-Pets", category: "DC", page: DC },
    { name: "Joker", category: "DC", page: DC },
    { name: "Joker: Folie à Deux", category: "DC", page: DC },
    { name: "Shazam!", category: "DC", page: DC },
    { name: "Shazam! Fury of the Gods", category: "DC", page: DC },
    { name: "Blue Beetle", category: "DC", page: DC },
    { name: "Green Lantern", category: "DC", page: DC },
    { name: "Man of Steel", category: "DC", page: DC },
    { name: "Superman", category: "DC", page: DC },
    { name: "Batman v Superman: Dawn of Justice", category: "DC", page: DC },
    { name: "Black Adam", category: "DC", page: DC },
    { name: "Wonder Woman", category: "DC", page: DC },
    { name: "Wonder Woman 1984", category: "DC", page: DC },
    { name: "Zack Snyder's Justice League", category: "DC", page: DC },
    { name: "Justice League", category: "DC", page: DC },

    // 🧟 ZOMBIE
    { name: "Evil Eye", category: "Zombie", page: ZOMBIE },
    { name: "iZombie", category: "Zombie", page: ZOMBIE },
    { name: "From", category: "Zombie", page: ZOMBIE },
    { name: "Fear the Walking Dead", category: "Zombie", page: ZOMBIE },
    { name: "Ash vs Evil Dead", category: "Zombie", page: ZOMBIE },
    { name: "Day of the Dead", category: "Zombie", page: ZOMBIE },
    { name: "The Last of Us", category: "Zombie", page: ZOMBIE },
    { name: "Rise of the Zombie", category: "Zombie", page: ZOMBIE },
    { name: "Zombie Reddy", category: "Zombie", page: ZOMBIE },
    { name: "Gangnam Zombie", category: "Zombie", page: ZOMBIE },
    { name: "Zombie Ka Aatank", category: "Zombie", page: ZOMBIE },
    { name: "Zombie Shark", category: "Zombie", page: ZOMBIE },
    { name: "Daybreakers", category: "Zombie", page: ZOMBIE },
    { name: "Death Valley", category: "Zombie", page: ZOMBIE },
    { name: "All of Us Are Dead", category: "Zombie", page: ZOMBIE },
    { name: "Resident Evil", category: "Zombie", page: ZOMBIE },
    { name: "Resident Evil: Apocalypse", category: "Zombie", page: ZOMBIE },
    { name: "Resident Evil: Extinction", category: "Zombie", page: ZOMBIE },
    { name: "Resident Evil: Afterlife", category: "Zombie", page: ZOMBIE },
    { name: "Resident Evil: Retribution", category: "Zombie", page: ZOMBIE },
    { name: "Resident Evil: The Final Chapter", category: "Zombie", page: ZOMBIE },
    { name: "Zombie Apocalypse", category: "Zombie", page: ZOMBIE },
    { name: "Zombie Town", category: "Zombie", page: ZOMBIE },
    { name: "World War Four", category: "Zombie", page: ZOMBIE },

    // 🤖 TRANSFORMERS
    { name: "Bumblebee", category: "Transformers", page: TRANSFORMERS },
    { name: "Transformers", category: "Transformers", page: TRANSFORMERS },
    { name: "Transformers: Revenge of the Fallen", category: "Transformers", page: TRANSFORMERS },
    { name: "Transformers: Dark of the Moon", category: "Transformers", page: TRANSFORMERS },
    { name: "Transformers: Age of Extinction", category: "Transformers", page: TRANSFORMERS },
    { name: "Transformers: The Last Knight", category: "Transformers", page: TRANSFORMERS },
    { name: "Transformers: Rise of the Beasts", category: "Transformers", page: TRANSFORMERS },

    // ❤️ ROMANTIC
    { name: "Tere Ishq Mein", category: "Romantic", page: ROMANTIC },
    { name: "Spring Fever", category: "Romantic", page: ROMANTIC },
    { name: "Dragon", category: "Romantic", page: ROMANTIC },
    { name: "The Royals", category: "Romantic", page: ROMANTIC },
    { name: "Genie: Make a Wish", category: "Romantic", page: ROMANTIC },
    { name: "Titanic", category: "Romantic", page: ROMANTIC },
    { name: "Titanic 2", category: "Romantic", page: ROMANTIC },
    { name: "Aankhon Ki Gustaakhiyan", category: "Romantic", page: ROMANTIC },
    { name: "Raanjhanaa", category: "Romantic", page: ROMANTIC },
    { name: "Saiyaara", category: "Romantic", page: ROMANTIC },
    { name: "Dhadak", category: "Romantic", page: ROMANTIC },
    { name: "Dhadak 2", category: "Romantic", page: ROMANTIC },
    { name: "Param Sundari", category: "Romantic", page: ROMANTIC },
    { name: "Our Fault", category: "Romantic", page: ROMANTIC },
    { name: "Radhe Shyam", category: "Romantic", page: ROMANTIC },
    { name: "Bawaal", category: "Romantic", page: ROMANTIC },
    { name: "Haseen Dillruba", category: "Romantic", page: ROMANTIC },
    { name: "Mere Husband Ki Biwi", category: "Romantic", page: ROMANTIC },
    { name: "Mr. Bachchan", category: "Romantic", page: ROMANTIC },
    { name: "Tu Jhoothi Main Makkaar", category: "Romantic", page: ROMANTIC },
    { name: "Gutar Gu", category: "Romantic", page: ROMANTIC },
    { name: "My Fault: London", category: "Romantic", page: ROMANTIC },
    { name: "Tera Kya Hoga Lovely", category: "Romantic", page: ROMANTIC },
    { name: "Sita Ramam", category: "Romantic", page: ROMANTIC },
    { name: "Premalu", category: "Romantic", page: ROMANTIC },
    { name: "Sanam Teri Kasam", category: "Romantic", page: ROMANTIC },
    { name: "Dada", category: "Romantic", page: ROMANTIC },
    { name: "Aap Jaisa Koi", category: "Romantic", page: ROMANTIC },
    { name: "De De Pyaar De", category: "Romantic", page: ROMANTIC },
    { name: "De De Pyaar De 2", category: "Romantic", page: ROMANTIC }
];